[build]
  publish = "frontend/build"
  command = "npm run build"
  functions = "frontend/backend"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200
  force = false

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200
  force = false