functionsDirectory = "C:\\Users\\acer\\Downloads\\pihealth360\\DemoMain\\frontend\\backend"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\acer\\Downloads\\pihealth360\\DemoMain\\frontend\\build"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
base = "C:\\Users\\acer\\Downloads\\pihealth360\\DemoMain"
functions = "C:\\Users\\acer\\Downloads\\pihealth360\\DemoMain\\frontend\\backend"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"
NODE_OPTIONS = "--openssl-legacy-provider"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/validation-key.txt"
to = "/validation-key.txt"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/privacy"
to = "/privacy.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/terms"
to = "/terms.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]